export const LOAN_DATA_REQUEST = "LOAN_DATA_REQUEST"
export const LOAN_DATA_SUCCESS = "LOAN_DATA_SUCCESS"
export const LOAN_DATA_ERROR = "LOAN_DATA_ERROR"


export const ALL_USER_REQUEST = "ALL_USER_REQUEST"
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS"
export const ALL_USER_ERROR = "ALL_USER_ERROR"